config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact-me', to: 'pages#contact'
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0,published: 1}
    extend FriendlyId
    friendly_id :title,use: :slugged
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

include SetSource
# include CurrentUserConcern

include DefaultPageContent

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]
  layout "blog"
  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
    @page_title = "My Portfolio Blogs"
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: "Your Post is now live" }
         else
        format.html { render :new, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: "Blog was successfully updated." }
          else
        format.html { render :edit, status: :unprocessable_entity }
         end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Post was removed" }
      format.json { head :no_content }
    end
  end

  def toggle_status
   if @blog.draft?
      @blog.published!
  elsif  @blog.published?
      @blog.draft!
  end
    redirect_to blogs_url, notice: "Post status has been  updated." 
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end

    
end

app/controllers/concerns/current_user_concern.rb
module CurrentUSerConcern

    extend ActiveSupport::Concern

    
# def current_user
#     super || guest_user
# end

# def guest_user

#     OpenStruct.new(name: "Guest User",first_name: "Guest",last_name:"User",email:"guest@example.com")

# end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
    extend ActiveSupport::Concern

included do
    before_action :set_title_defaults
end

def set_title_defaults
        @page_title = "DevcampPortfolio  | My Portfolio Website"
        @seo_keywords = "Yamin Portfolio"
    end
end

app/controllers/concerns/set_source.rb
module SetSource 
    extend ActiveSupport::Concern

included do
   before_action :set_source
end

def set_source
   session[:source] = params[:q] if params[:q]
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
layout "portfolio"

    def index
        @portfolio_items = Portfolio.all
    end

    def new 
        @portfolio_item = Portfolio.new
    end

    def create
        @portfolio_item = Portfolio.new(portfolio_params)
    
        respond_to do |format|
          if @portfolio_item.save
            format.html { redirect_to portfolios_path, notice: "Your Portfolio Item  is now live" }
             else
            format.html { render :new }
            end
        end
      end

      def edit 
        @portfolio_item = Portfolio.find(params[:id])
      end

      def update
        @portfolio_item = Portfolio.find(params[:id])
        
        respond_to do |format|
          if @portfolio_item .update(portfolio_params)
            format.html { redirect_to portfolios_path, notice: "This record successfully updated." }
              else
            format.html { render :edit, status: :unprocessable_entity }
             end
        end
      end

      def show
        @portfolio_item = Portfolio.find(params[:id])
      end

      def destroy
        #Perform the lookup
        @portfolio_item = Portfolio.find(params[:id])
       
         #Destroy/delete the record
        @portfolio_item.destroy

        # Redirect 
       respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Record was removed" }

    end
      end

      private def portfolio_params
        params.require(:portfolio).permit(:title, 
                                          :subtitle,
                                          :body,
                                          :image)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def sample_helper
        "<p>My Helper</p>"
    end

   def create_content
     content_tag(:div, "My content", class: "my-class")
   end

   def source_helper(layout_name)
    if session[:source]
       greeting = "Thanks for visiting me from #{session[:source]} and you are on the #{layout_name} layout"
       content_tag(:p,greeting,class: "source_greeting")
    end 
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<tr>
        <td><%= blog.title %></td>
        <td>Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Delete Post ', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Blog Title</th>
      <th>Date</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @blogs %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <meta name="keywords" content= "<%= @seo_keywords %>" />
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/nav", location: 'top' %>

  
    <%= yield %>
    

   <%= source_helper("application") %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <meta name="keywords" content= "<%= @seo_keywords %>" />
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  

    <%= yield %>

    <%= render "shared/nav", location: 'bottom'%>

    <%= source_helper("blog") %>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %> </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <meta name="keywords" content= "<%= @seo_keywords %>" />
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <%= render "shared/nav" ,location: 'top' %>

    <%= yield %>

    

    <%= source_helper("portfolio") %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p><%= number_to_phone "44444444444" %></p>
<p><%= number_to_currency "150" %></p>
<p><%= number_to_percentage "80.4" %></p>
<p><%= number_with_delimiter "1147182561285" %></p>

app/views/pages/home.html.erb
<h1>Home page</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1> Blog Post</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

<%= sample_helper %>

<%= content_tag :h1, class: "my-special-class" do %>
   Hi,I'm in paragraph tag 
<% end %>

<p>Hi,I'm in paragraph tag </p>

<%= create_content %>

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>
  
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/portfolios/_portfolio_item.html.erb
<p><%= link_to portfolio_item.title,portfolio_show_path(portfolio_item) %></p>    
    <p><%= portfolio_item.subtitle %></p>    
    <p><%= portfolio_item.body %></p>    
    <p><%= portfolio_item.main_image %></p>    
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %></p>    

    <%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
    <a href="/portfolios/<%= portfolio_item.id%>/edit">Edit Two</a>
    <%= link_to 'Delete Portfolio ITem ', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
      
    

app/views/portfolios/edit.html.erb
<h1>Edit this  Portfolio item </h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1> Portfolio Items </h1>
<a href= "portfolios/new" title="">Creat New Item</a>

<%= link_to "Create New Item", new_portfolio_path %>

<%= link_to "Create New Item", new_portfolio_url ,subdomain: "my_subdomain" %>

<p>
    <%= new_portfolio_path %>
</p>

<p>
    <%= new_portfolio_url %>
</p>

<%= render partial: "portfolio_item" , collection: @portfolio_items %>
    

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio </h1>

<%= render 'form', portfolio_item: @portfolio_item %>

  

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image if !@portfolio_item.main_image.nil? %>

<h1><%=  @portfolio_item.title %></h1>

<em><%=  @portfolio_item.subtitle %></em

<p><%=  @portfolio_item.body %></p>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
       <div><%= link_to "Home", root_path %></div>
       <div><%= link_to "About", about_me_path %></div>
       <div><%= link_to "Contact", contact_me_path %></div>
       <div><%= link_to "Blogs", blogs_path %></div>
       <div><%= link_to "Portfolio", portfolios_path %></div>
  
  </div>